# Generated by Django 4.1.7 on 2023-06-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
